karakun/karakun.github.io

_posts/2018-06-25-java-releases.md

Viele whitespace  Änderungen. Bitte nicht von dem grossen Diff abschrecken lassen :wink: 
Das wenigste sind klare Korrekturen. Vieles darfst du als Vorschlag sehen. Fragen beantworte ich gerne.

small improvements to java release pos

---

about.md

WIP: changes for about page

---

_posts/2018-06-29-flavoured-artefacts-with-gradle.md

replace smiley

---

_includes/footer.html
_includes/header.html
_includes/webstats.html
_layouts/home.html
_layouts/post.html
_layouts/talks.html
cookie-policy.md
privacy-policy.md

(Hopefully) better HTML ;)

---

_layouts/people.html

book link removed

---

_layouts/about.html

About page: Designer

---

color-scheme.md
private.md

Color-Scheme

---

jdks.md
webstart.md

Infos and download links to OpenJDK

Open jdk download

---

_includes/footer.html
_includes/header.html
about.md
books.md
jdks.md
talks.md
webstart.md

added 'order' attribute to order links in page menu

Pages ordered in menu

---

jdks.md

SAP added to JDK list

---

_people/simon.md

Simon added

---

_includes/head.html

Fix for https://github.com/karakun/karakun.github.io/issues/70

Cleanup SEO Tags

---

jdks.md

removed link from menu since the content isn't up to date anymore.

removed OpenJDK from menu

---

_data/talks.yml

"Multidevice" talk added

---

_data/talks.yml

Java APIs Talk updated

---

_posts/2018-11-04-wjax-2018.md

Improvements from @madmas out of #93

add improvements for W-JAX post

---

_layouts/people.html
_people/hendrik.md

Mail, Twitter, GitHub added
Talks & Books fixed

some more info on people pages

---

_people/mittie.md
_posts/2018-06-25-java-releases.md
_posts/2018-06-29-flavoured-artefacts-with-gradle.md
_posts/2018-09-16-java-11-licence.md
_posts/2018-09-16-jc-java-article.md
_posts/2018-09-25-java11-release-event.md
_posts/2018-10-20-karakun-at-oracle-code-one.md
_posts/2018-11-01-multidevice-controls.md
_posts/2018-11-04-jfx-day.md
_posts/2018-11-04-wjax-2018.md
_posts/2018-11-08-react-training-announced.md
_posts/2018-11-23-amazon-corretto.md

all headers defined

---

_posts/2019-01-03-integration-docker.md

Some changes to the Docker article after my review.
Will be merged into #51

Review changes

---

_data/talks.yml

YouTube links to talks added

---

_data/images.yml
_layouts/about.html

References to images in about page are generated by yml file

image reference in yml file

---

_posts/2019-01-13-video-modular-monoliths-by-simon-brown.md

@sclassen some changes on your initial layout / text. Not perfect but I like the structure more.

Review of Video-Post

---

README.md

added installing instructions and links

readme.md update: initial setup

---

_posts/2019-01-25-security-exploits.md

2019-01-25 security exploits - updates

---

_data/talks.yml

c't <webdev> talks added ... funny escaping necessary because of the nice characters in the name 😄

c't <webdev> talks added

---

_layouts/home.html

fix for https://github.com/karakun/karakun.github.io/issues/169

removed reading time on overview

---

_layouts/post.html

Instead of:
Now it will look like this:

Adds hyperlinked categories to each post with category size counter

---

_sass/bulma/elements/tag.sass

https://github.com/karakun/karakun.github.io/pull/172#issuecomment-747528641 /cc @hendrikebbers

Changing the tag styling on :hover

---

_data/talks.yml
_layouts/talks.html

Authors can now be entered as a collection i.e. `['hendrik', 'stephanc']` which will be displayed as follows:
Closes #180

Add support for multiple authors per talk

---

README.md

in order to let ppl looking for it know how to serve the drafts

add draft.sh hint to readme

---

Gemfile
Gemfile.lock

See: https://github.com/jekyll/jekyll/issues/8523

Fix local setup when using Ruby 3.0

---

_layouts/books.html
_layouts/talk.html
_layouts/talks.html

Also clean up on books and talks pages

Clean up books and talks

---

_config.yml
_includes/footer.html

Instead of changing it manually.

Automate footer copyright information with current year

---

_layouts/people.html
_people/markus.md

Add capabilities to add mastodon and linkedin links with icons

---

_people/christopher.md

- Added "alumni=true" to Christophers bio so he is removed from the employee list
- changed the bio description

Removed Christopher from employee list

---

rico.md

as discussed, I have removed the menu item "Rico" from the top level menu

removed rico from top level menu

---

_posts/2024-03-02-why-software-testing-is-a-waste-of-time-unpacked.md
_posts/2024-03-18-why-software-testing-is-a-waste-of-time-unpacked.md

@kress04 feel free to adjust the publishing date and merge it at a later point in time if you feel like this one is too close to Markus' post ;)

Add blog article "Why Software Testing Is a Waste of Time: Unpacking the Paradox"

---

_posts/2025-02-25-java-enterprise.md

title: 'Java: The Brave Companion in the World of Enterprise Software Solutions!'
authors: [ 'ixchel' ]
featuredImage: adopt-free
excerpt: "The relentless march of technology demands that we design enterprise solutions not just for today, but for a future we can only partially imagine. Java, with its commitment to a regular release cadence and a focus on evolution, stands as a shining example of how to build software that can adapt, grow, and remain relevant for years to come. By embracing change, fostering innovation, and prioritizing sustainability, we can create systems that not only enhance human life but also contribute to the well-being of our planet."
permalink: '/2025/02/25/java-enterprise.html'
categories: [ Java ]

Java: The Brave Companion in the World of Enterprise Software Solutions!
